version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      PC_PORT: 8080
      PC_POSTGRES: postgres://postgres:postgres@db:5432/privatecaptcha?sslmode=disable
    depends_on:
      - db
    networks:
      - db_network

  db:
    image: postgres
    environment:
      POSTGRES_DB: privatecaptcha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

networks:
  db_network:

volumes:
  postgres_data_volume:
