// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	common "github.com/PrivateCaptcha/PrivateCaptcha/pkg/common"
	puzzle "github.com/PrivateCaptcha/PrivateCaptcha/pkg/puzzle"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi(in *jlexer.Lexer, out *operationResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = common.StatusCode(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi(out *jwriter.Writer, in operationResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v operationResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v operationResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *operationResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *operationResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi1(in *jlexer.Lexer, out *apiPropertyOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "domain":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Domain = string(in.String())
			}
		case "sitekey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sitekey = string(in.String())
			}
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = int(in.Int())
			}
		case "growth":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Growth = string(in.String())
			}
		case "validity_seconds":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ValiditySeconds = int(in.Int())
			}
		case "allow_subdomains":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AllowSubdomains = bool(in.Bool())
			}
		case "allow_localhost":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AllowLocalhost = bool(in.Bool())
			}
		case "max_replay_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxReplayCount = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi1(out *jwriter.Writer, in apiPropertyOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix)
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"sitekey\":"
		out.RawString(prefix)
		out.String(string(in.Sitekey))
	}
	if in.Level != 0 {
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.Int(int(in.Level))
	}
	if in.Growth != "" {
		const prefix string = ",\"growth\":"
		out.RawString(prefix)
		out.String(string(in.Growth))
	}
	if in.ValiditySeconds != 0 {
		const prefix string = ",\"validity_seconds\":"
		out.RawString(prefix)
		out.Int(int(in.ValiditySeconds))
	}
	if in.AllowSubdomains {
		const prefix string = ",\"allow_subdomains\":"
		out.RawString(prefix)
		out.Bool(bool(in.AllowSubdomains))
	}
	if in.AllowLocalhost {
		const prefix string = ",\"allow_localhost\":"
		out.RawString(prefix)
		out.Bool(bool(in.AllowLocalhost))
	}
	if in.MaxReplayCount != 0 {
		const prefix string = ",\"max_replay_count\":"
		out.RawString(prefix)
		out.Int(int(in.MaxReplayCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v apiPropertyOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v apiPropertyOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *apiPropertyOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *apiPropertyOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi1(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi2(in *jlexer.Lexer, out *apiOrgPropertyOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "sitekey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sitekey = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi2(out *jwriter.Writer, in apiOrgPropertyOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"sitekey\":"
		out.RawString(prefix)
		out.String(string(in.Sitekey))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v apiOrgPropertyOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v apiOrgPropertyOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *apiOrgPropertyOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *apiOrgPropertyOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi2(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi3(in *jlexer.Lexer, out *apiOrgOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi3(out *jwriter.Writer, in apiOrgOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v apiOrgOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v apiOrgOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *apiOrgOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *apiOrgOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi3(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi4(in *jlexer.Lexer, out *apiAsyncTaskResultOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "finished":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Finished = bool(in.Bool())
			}
		case "result":
			if m, ok := out.Result.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Result.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Result = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi4(out *jwriter.Writer, in apiAsyncTaskResultOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"finished\":"
		out.RawString(prefix)
		out.Bool(bool(in.Finished))
	}
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix)
		if m, ok := in.Result.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Result.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Result))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v apiAsyncTaskResultOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v apiAsyncTaskResultOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *apiAsyncTaskResultOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *apiAsyncTaskResultOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi4(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi5(in *jlexer.Lexer, out *apiAsyncTaskOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi5(out *jwriter.Writer, in apiAsyncTaskOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v apiAsyncTaskOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v apiAsyncTaskOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *apiAsyncTaskOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *apiAsyncTaskOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi5(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi6(in *jlexer.Lexer, out *VerifyResponseRecaptchaV3) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Score = float64(in.Float64())
			}
		case "action":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Action = string(in.String())
			}
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = bool(in.Bool())
			}
		case "error-codes":
			if in.IsNull() {
				in.Skip()
				out.ErrorCodes = nil
			} else {
				in.Delim('[')
				if out.ErrorCodes == nil {
					if !in.IsDelim(']') {
						out.ErrorCodes = make([]string, 0, 4)
					} else {
						out.ErrorCodes = []string{}
					}
				} else {
					out.ErrorCodes = (out.ErrorCodes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.ErrorCodes = append(out.ErrorCodes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "challenge_ts":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ChallengeTS).UnmarshalJSON(data))
				}
			}
		case "hostname":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Hostname = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi6(out *jwriter.Writer, in VerifyResponseRecaptchaV3) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"score\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Score))
	}
	{
		const prefix string = ",\"action\":"
		out.RawString(prefix)
		out.String(string(in.Action))
	}
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix)
		out.Bool(bool(in.Success))
	}
	if len(in.ErrorCodes) != 0 {
		const prefix string = ",\"error-codes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.ErrorCodes {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"challenge_ts\":"
		out.RawString(prefix)
		out.Raw((in.ChallengeTS).MarshalJSON())
	}
	{
		const prefix string = ",\"hostname\":"
		out.RawString(prefix)
		out.String(string(in.Hostname))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VerifyResponseRecaptchaV3) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VerifyResponseRecaptchaV3) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VerifyResponseRecaptchaV3) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VerifyResponseRecaptchaV3) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi6(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi7(in *jlexer.Lexer, out *VerifyResponseRecaptchaV2) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = bool(in.Bool())
			}
		case "error-codes":
			if in.IsNull() {
				in.Skip()
				out.ErrorCodes = nil
			} else {
				in.Delim('[')
				if out.ErrorCodes == nil {
					if !in.IsDelim(']') {
						out.ErrorCodes = make([]string, 0, 4)
					} else {
						out.ErrorCodes = []string{}
					}
				} else {
					out.ErrorCodes = (out.ErrorCodes)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.ErrorCodes = append(out.ErrorCodes, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "challenge_ts":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ChallengeTS).UnmarshalJSON(data))
				}
			}
		case "hostname":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Hostname = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi7(out *jwriter.Writer, in VerifyResponseRecaptchaV2) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Success))
	}
	if len(in.ErrorCodes) != 0 {
		const prefix string = ",\"error-codes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.ErrorCodes {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"challenge_ts\":"
		out.RawString(prefix)
		out.Raw((in.ChallengeTS).MarshalJSON())
	}
	{
		const prefix string = ",\"hostname\":"
		out.RawString(prefix)
		out.String(string(in.Hostname))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VerifyResponseRecaptchaV2) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VerifyResponseRecaptchaV2) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VerifyResponseRecaptchaV2) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VerifyResponseRecaptchaV2) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi7(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi8(in *jlexer.Lexer, out *VerificationResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = bool(in.Bool())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = puzzle.VerifyError(in.Int())
			}
		case "origin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Origin = string(in.String())
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Timestamp).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi8(out *jwriter.Writer, in VerificationResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Success))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.Int(int(in.Code))
	}
	if in.Origin != "" {
		const prefix string = ",\"origin\":"
		out.RawString(prefix)
		out.String(string(in.Origin))
	}
	if true {
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Raw((in.Timestamp).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VerificationResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VerificationResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VerificationResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VerificationResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi8(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi9(in *jlexer.Lexer, out *ResponseMetadata) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = common.StatusCode(in.Int())
			}
		case "request_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RequestID = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi9(out *jwriter.Writer, in ResponseMetadata) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	if in.RequestID != "" {
		const prefix string = ",\"request_id\":"
		out.RawString(prefix)
		out.String(string(in.RequestID))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseMetadata) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseMetadata) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseMetadata) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseMetadata) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi9(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi10(in *jlexer.Lexer, out *Pagination) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "page":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Page = int(in.Int())
			}
		case "per_page":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PerPage = int(in.Int())
			}
		case "has_more":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HasMore = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi10(out *jwriter.Writer, in Pagination) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"page\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Page))
	}
	{
		const prefix string = ",\"per_page\":"
		out.RawString(prefix)
		out.Int(int(in.PerPage))
	}
	{
		const prefix string = ",\"has_more\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasMore))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Pagination) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Pagination) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Pagination) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Pagination) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi10(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi11(in *jlexer.Lexer, out *APIResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "meta":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Meta).UnmarshalEasyJSON(in)
			}
		case "data":
			if m, ok := out.Data.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Data.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Data = in.Interface()
			}
		case "pagination":
			if in.IsNull() {
				in.Skip()
				out.Pagination = nil
			} else {
				if out.Pagination == nil {
					out.Pagination = new(Pagination)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Pagination).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi11(out *jwriter.Writer, in APIResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"meta\":"
		out.RawString(prefix[1:])
		(in.Meta).MarshalEasyJSON(out)
	}
	if in.Data != nil {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if m, ok := in.Data.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Data.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Data))
		}
	}
	if in.Pagination != nil {
		const prefix string = ",\"pagination\":"
		out.RawString(prefix)
		(*in.Pagination).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v APIResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APIResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgApi11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APIResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APIResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgApi11(l, v)
}
