package common

const (
	HeaderContentType     = "Content-Type"
	HeaderContentLength   = "Content-Length"
	HeaderAuthorization   = "Authorization"
	ContentTypePlain      = "text/plain"
	ContentTypeJSON       = "application/json"
	ContentTypeURLEncoded = "application/x-www-form-urlencoded"
	ParamSiteKey          = "sitekey"
	ParamSecret           = "secret"
	ParamResponse         = "response"
	ParamEmail            = "email"
	ParamName             = "name"
	ParamCsrfToken        = "csrf_token"
	ParamVerificationCode = "vcode"
	ParamDomain           = "domain"
	ParamDifficulty       = "difficulty"
	ParamGrowth           = "growth"
	ParamTab              = "tab"
	ParamNew              = "new"
	ParamMonths           = "months"
	ParamCategory         = "category"
	ParamMessage          = "message"
)
