package common

const (
	StageProd             = "prod"
	StageDev              = "dev"
	StageTest             = "test"
	HeaderContentType     = "Content-Type"
	HeaderContentLength   = "Content-Length"
	HeaderAuthorization   = "Authorization"
	HeaderCSRFToken       = "X-CSRF-Token"
	HeaderCaptchaVersion  = "X-PC-Captcha-Version"
	ContentTypePlain      = "text/plain"
	ContentTypeJSON       = "application/json"
	ContentTypeURLEncoded = "application/x-www-form-urlencoded"
	ParamSiteKey          = "sitekey"
	ParamSecret           = "secret"
	ParamResponse         = "response"
	ParamEmail            = "email"
	ParamName             = "name"
	ParamCSRFToken        = "csrf_token"
	ParamVerificationCode = "vcode"
	ParamDomain           = "domain"
	ParamDifficulty       = "difficulty"
	ParamGrowth           = "growth"
	ParamTab              = "tab"
	ParamNew              = "new"
	ParamMonths           = "months"
	ParamCategory         = "category"
	ParamMessage          = "message"
	ParamProduct          = "product"
	ParamYearly           = "yearly"
	ParamPrice            = "price"
	ParamOrg              = "org"
	ParamUser             = "user"
	ParamPeriod           = "period"
	ParamProperty         = "property"
	ParamKey              = "key"
	ParamCode             = "code"
	ConfigRateLimitHeader = "RATE_LIMIT_HEADER"
)
