package common

const (
	DefaultOrgName              = "My Organization"
	PrivateCaptcha              = "Private Captcha"
	StageProd                   = "prod"
	StageDev                    = "dev"
	StageStaging                = "staging"
	StageTest                   = "test"
	HeaderCDNTag                = "CDN-Tag"
	HeaderContentType           = "Content-Type"
	HeaderContentLength         = "Content-Length"
	HeaderAuthorization         = "Authorization"
	HeaderCSRFToken             = "X-CSRF-Token"
	HeaderCaptchaVersion        = "X-PC-Captcha-Version"
	HeaderCaptchaCompat         = "X-Captcha-Compat-Version"
	HeaderAPIKey                = "X-API-Key"
	ContentTypePlain            = "text/plain"
	ContentTypeHTML             = "text/html; charset=utf-8"
	ContentTypeJSON             = "application/json"
	ContentTypeURLEncoded       = "application/x-www-form-urlencoded"
	ParamSiteKey                = "sitekey"
	ParamResponse               = "response"
	ParamEmail                  = "email"
	ParamName                   = "name"
	ParamCSRFToken              = "csrf_token"
	ParamVerificationCode       = "vcode"
	ParamDomain                 = "domain"
	ParamDifficulty             = "difficulty"
	ParamGrowth                 = "growth"
	ParamTab                    = "tab"
	ParamNew                    = "new"
	ParamMonths                 = "months"
	ParamCategory               = "category"
	ParamMessage                = "message"
	ParamSubject                = "subject"
	ParamProduct                = "product"
	ParamYearly                 = "yearly"
	ParamPrice                  = "price"
	ParamOrg                    = "org"
	ParamUser                   = "user"
	ParamPeriod                 = "period"
	ParamProperty               = "property"
	ParamKey                    = "key"
	ParamCode                   = "code"
	ParamID                     = "id"
	ConfigRateLimitHeader       = "RATE_LIMIT_HEADER"
	ConfigPresharedSecretHeader = "PRESHARED_SECRET_HEADER"
	AreaPuzzle                  = "PUZZLE"
	AreaDefault                 = "DEFAULT"
)
