package common

const (
	PuzzleEndpoint              = "puzzle"
	VerifyEndpoint              = "verify"
	LoginEndpoint               = "login"
	TwoFactorEndpoint           = "2fa"
	ResendEndpoint              = "resend"
	ErrorEndpoint               = "error"
	RegisterEndpoint            = "signup"
	ExpiredEndpoint             = "expired"
	SettingsEndpoint            = "settings"
	LogoutEndpoint              = "logout"
	PropertyEndpoint            = "property"
	OrgEndpoint                 = "org"
	DashboardEndpoint           = "dashboard"
	NewEndpoint                 = "new"
	StatsEndpoint               = "stats"
	TabEndpoint                 = "tab"
	ReportsEndpoint             = "reports"
	IntegrationsEndpoint        = "integrations"
	EditEndpoint                = "edit"
	DeleteEndpoint              = "delete"
	MembersEndpoint             = "members"
	GeneralEndpoint             = "general"
	EmailEndpoint               = "email"
	UserEndpoint                = "user"
	APIKeysEndpoint             = "apikeys"
	SupportEndpoint             = "support"
	PaddleSubscriptionCreated   = "subscr_created"
	PaddleSubscriptionUpdated   = "subscr_updated"
	PaddleSubscriptionCancelled = "subscr_cancelled"
	BillingEndpoint             = "billing"
	CancelEndpoint              = "cancel"
	UpdateEndpoint              = "update"
)
