// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package portal

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(in *jlexer.Lexer, out *PropertyStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "requested":
			if in.IsNull() {
				in.Skip()
				out.Requested = nil
			} else {
				in.Delim('[')
				if out.Requested == nil {
					if !in.IsDelim(']') {
						out.Requested = make([]*PropertyStatsPoint, 0, 8)
					} else {
						out.Requested = []*PropertyStatsPoint{}
					}
				} else {
					out.Requested = (out.Requested)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *PropertyStatsPoint
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(PropertyStatsPoint)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v1).UnmarshalEasyJSON(in)
						}
					}
					out.Requested = append(out.Requested, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "verified":
			if in.IsNull() {
				in.Skip()
				out.Verified = nil
			} else {
				in.Delim('[')
				if out.Verified == nil {
					if !in.IsDelim(']') {
						out.Verified = make([]*PropertyStatsPoint, 0, 8)
					} else {
						out.Verified = []*PropertyStatsPoint{}
					}
				} else {
					out.Verified = (out.Verified)[:0]
				}
				for !in.IsDelim(']') {
					var v2 *PropertyStatsPoint
					if in.IsNull() {
						in.Skip()
						v2 = nil
					} else {
						if v2 == nil {
							v2 = new(PropertyStatsPoint)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v2).UnmarshalEasyJSON(in)
						}
					}
					out.Verified = append(out.Verified, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(out *jwriter.Writer, in PropertyStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"requested\":"
		out.RawString(prefix[1:])
		if in.Requested == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Requested {
				if v3 > 0 {
					out.RawByte(',')
				}
				if v4 == nil {
					out.RawString("null")
				} else {
					(*v4).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"verified\":"
		out.RawString(prefix)
		if in.Verified == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Verified {
				if v5 > 0 {
					out.RawByte(',')
				}
				if v6 == nil {
					out.RawString("null")
				} else {
					(*v6).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PropertyStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PropertyStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PropertyStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PropertyStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(in *jlexer.Lexer, out *PropertyStatsPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "x":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = int64(in.Int64())
			}
		case "y":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(out *jwriter.Writer, in PropertyStatsPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Date))
	}
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix)
		out.Int(int(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PropertyStatsPoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PropertyStatsPoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PropertyStatsPoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PropertyStatsPoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(in *jlexer.Lexer, out *PropertyRuleStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "usage":
			if in.IsNull() {
				in.Skip()
				out.Usage = nil
			} else {
				in.Delim('[')
				if out.Usage == nil {
					if !in.IsDelim(']') {
						out.Usage = make([]*PropertyRuleStatsPoint, 0, 8)
					} else {
						out.Usage = []*PropertyRuleStatsPoint{}
					}
				} else {
					out.Usage = (out.Usage)[:0]
				}
				for !in.IsDelim(']') {
					var v7 *PropertyRuleStatsPoint
					if in.IsNull() {
						in.Skip()
						v7 = nil
					} else {
						if v7 == nil {
							v7 = new(PropertyRuleStatsPoint)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v7).UnmarshalEasyJSON(in)
						}
					}
					out.Usage = append(out.Usage, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(out *jwriter.Writer, in PropertyRuleStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"usage\":"
		out.RawString(prefix[1:])
		if in.Usage == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Usage {
				if v8 > 0 {
					out.RawByte(',')
				}
				if v9 == nil {
					out.RawString("null")
				} else {
					(*v9).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PropertyRuleStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PropertyRuleStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PropertyRuleStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PropertyRuleStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(in *jlexer.Lexer, out *PropertyRuleStatsPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "x":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = int64(in.Int64())
			}
		case "y":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(out *jwriter.Writer, in PropertyRuleStatsPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Date))
	}
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix)
		out.Int(int(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PropertyRuleStatsPoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PropertyRuleStatsPoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PropertyRuleStatsPoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PropertyRuleStatsPoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(in *jlexer.Lexer, out *FormStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "success":
			if in.IsNull() {
				in.Skip()
				out.Success = nil
			} else {
				in.Delim('[')
				if out.Success == nil {
					if !in.IsDelim(']') {
						out.Success = make([]*PropertyStatsPoint, 0, 8)
					} else {
						out.Success = []*PropertyStatsPoint{}
					}
				} else {
					out.Success = (out.Success)[:0]
				}
				for !in.IsDelim(']') {
					var v10 *PropertyStatsPoint
					if in.IsNull() {
						in.Skip()
						v10 = nil
					} else {
						if v10 == nil {
							v10 = new(PropertyStatsPoint)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v10).UnmarshalEasyJSON(in)
						}
					}
					out.Success = append(out.Success, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "failure":
			if in.IsNull() {
				in.Skip()
				out.Failure = nil
			} else {
				in.Delim('[')
				if out.Failure == nil {
					if !in.IsDelim(']') {
						out.Failure = make([]*PropertyStatsPoint, 0, 8)
					} else {
						out.Failure = []*PropertyStatsPoint{}
					}
				} else {
					out.Failure = (out.Failure)[:0]
				}
				for !in.IsDelim(']') {
					var v11 *PropertyStatsPoint
					if in.IsNull() {
						in.Skip()
						v11 = nil
					} else {
						if v11 == nil {
							v11 = new(PropertyStatsPoint)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v11).UnmarshalEasyJSON(in)
						}
					}
					out.Failure = append(out.Failure, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(out *jwriter.Writer, in FormStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix[1:])
		if in.Success == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.Success {
				if v12 > 0 {
					out.RawByte(',')
				}
				if v13 == nil {
					out.RawString("null")
				} else {
					(*v13).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"failure\":"
		out.RawString(prefix)
		if in.Failure == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Failure {
				if v14 > 0 {
					out.RawByte(',')
				}
				if v15 == nil {
					out.RawString("null")
				} else {
					(*v15).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FormStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FormStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FormStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FormStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(in *jlexer.Lexer, out *AccountStatsSeries) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(out *jwriter.Writer, in AccountStatsSeries) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Int(int(in.Index))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountStatsSeries) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountStatsSeries) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountStatsSeries) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountStatsSeries) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal6(in *jlexer.Lexer, out *AccountStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "series":
			if in.IsNull() {
				in.Skip()
				out.Series = nil
			} else {
				in.Delim('[')
				if out.Series == nil {
					if !in.IsDelim(']') {
						out.Series = make([]*AccountStatsSeries, 0, 8)
					} else {
						out.Series = []*AccountStatsSeries{}
					}
				} else {
					out.Series = (out.Series)[:0]
				}
				for !in.IsDelim(']') {
					var v16 *AccountStatsSeries
					if in.IsNull() {
						in.Skip()
						v16 = nil
					} else {
						if v16 == nil {
							v16 = new(AccountStatsSeries)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v16).UnmarshalEasyJSON(in)
						}
					}
					out.Series = append(out.Series, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]*AccountStatsPoint, 0, 8)
					} else {
						out.Data = []*AccountStatsPoint{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v17 *AccountStatsPoint
					if in.IsNull() {
						in.Skip()
						v17 = nil
					} else {
						if v17 == nil {
							v17 = new(AccountStatsPoint)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v17).UnmarshalEasyJSON(in)
						}
					}
					out.Data = append(out.Data, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal6(out *jwriter.Writer, in AccountStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"series\":"
		out.RawString(prefix[1:])
		if in.Series == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.Series {
				if v18 > 0 {
					out.RawByte(',')
				}
				if v19 == nil {
					out.RawString("null")
				} else {
					(*v19).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Data {
				if v20 > 0 {
					out.RawByte(',')
				}
				if v21 == nil {
					out.RawString("null")
				} else {
					(*v21).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal6(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal7(in *jlexer.Lexer, out *AccountStatsRawPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "OrgID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrgID = int32(in.Int32())
			}
		case "Date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = int64(in.Int64())
			}
		case "Value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal7(out *jwriter.Writer, in AccountStatsRawPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"OrgID\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.OrgID))
	}
	{
		const prefix string = ",\"Date\":"
		out.RawString(prefix)
		out.Int64(int64(in.Date))
	}
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix)
		out.Int(int(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountStatsRawPoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountStatsRawPoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountStatsRawPoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountStatsRawPoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal7(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal8(in *jlexer.Lexer, out *AccountStatsPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "x":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = int64(in.Int64())
			}
		case "y":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int(in.Int())
			}
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Series = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal8(out *jwriter.Writer, in AccountStatsPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Date))
	}
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix)
		out.Int(int(in.Value))
	}
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix)
		out.Int(int(in.Series))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountStatsPoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountStatsPoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountStatsPoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountStatsPoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal8(l, v)
}
