// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package portal

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(in *jlexer.Lexer, out *propertyStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "requested":
			if in.IsNull() {
				in.Skip()
				out.Requested = nil
			} else {
				in.Delim('[')
				if out.Requested == nil {
					if !in.IsDelim(']') {
						out.Requested = make([]*propertyStatsPoint, 0, 8)
					} else {
						out.Requested = []*propertyStatsPoint{}
					}
				} else {
					out.Requested = (out.Requested)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *propertyStatsPoint
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(propertyStatsPoint)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v1).UnmarshalEasyJSON(in)
						}
					}
					out.Requested = append(out.Requested, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "verified":
			if in.IsNull() {
				in.Skip()
				out.Verified = nil
			} else {
				in.Delim('[')
				if out.Verified == nil {
					if !in.IsDelim(']') {
						out.Verified = make([]*propertyStatsPoint, 0, 8)
					} else {
						out.Verified = []*propertyStatsPoint{}
					}
				} else {
					out.Verified = (out.Verified)[:0]
				}
				for !in.IsDelim(']') {
					var v2 *propertyStatsPoint
					if in.IsNull() {
						in.Skip()
						v2 = nil
					} else {
						if v2 == nil {
							v2 = new(propertyStatsPoint)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v2).UnmarshalEasyJSON(in)
						}
					}
					out.Verified = append(out.Verified, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(out *jwriter.Writer, in propertyStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"requested\":"
		out.RawString(prefix[1:])
		if in.Requested == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Requested {
				if v3 > 0 {
					out.RawByte(',')
				}
				if v4 == nil {
					out.RawString("null")
				} else {
					(*v4).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"verified\":"
		out.RawString(prefix)
		if in.Verified == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Verified {
				if v5 > 0 {
					out.RawByte(',')
				}
				if v6 == nil {
					out.RawString("null")
				} else {
					(*v6).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v propertyStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v propertyStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *propertyStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *propertyStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(in *jlexer.Lexer, out *propertyStatsPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "x":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = int64(in.Int64())
			}
		case "y":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(out *jwriter.Writer, in propertyStatsPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Date))
	}
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix)
		out.Int(int(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v propertyStatsPoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v propertyStatsPoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *propertyStatsPoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *propertyStatsPoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal1(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(in *jlexer.Lexer, out *accountStatsSeries) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(out *jwriter.Writer, in accountStatsSeries) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Int(int(in.Index))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v accountStatsSeries) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v accountStatsSeries) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *accountStatsSeries) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *accountStatsSeries) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal2(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(in *jlexer.Lexer, out *accountStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "series":
			if in.IsNull() {
				in.Skip()
				out.Series = nil
			} else {
				in.Delim('[')
				if out.Series == nil {
					if !in.IsDelim(']') {
						out.Series = make([]*accountStatsSeries, 0, 8)
					} else {
						out.Series = []*accountStatsSeries{}
					}
				} else {
					out.Series = (out.Series)[:0]
				}
				for !in.IsDelim(']') {
					var v7 *accountStatsSeries
					if in.IsNull() {
						in.Skip()
						v7 = nil
					} else {
						if v7 == nil {
							v7 = new(accountStatsSeries)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v7).UnmarshalEasyJSON(in)
						}
					}
					out.Series = append(out.Series, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]*accountStatsPoint, 0, 8)
					} else {
						out.Data = []*accountStatsPoint{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v8 *accountStatsPoint
					if in.IsNull() {
						in.Skip()
						v8 = nil
					} else {
						if v8 == nil {
							v8 = new(accountStatsPoint)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v8).UnmarshalEasyJSON(in)
						}
					}
					out.Data = append(out.Data, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(out *jwriter.Writer, in accountStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"series\":"
		out.RawString(prefix[1:])
		if in.Series == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Series {
				if v9 > 0 {
					out.RawByte(',')
				}
				if v10 == nil {
					out.RawString("null")
				} else {
					(*v10).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Data {
				if v11 > 0 {
					out.RawByte(',')
				}
				if v12 == nil {
					out.RawString("null")
				} else {
					(*v12).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v accountStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v accountStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *accountStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *accountStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal3(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(in *jlexer.Lexer, out *accountStatsRawPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "OrgID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrgID = int32(in.Int32())
			}
		case "Date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = int64(in.Int64())
			}
		case "Value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(out *jwriter.Writer, in accountStatsRawPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"OrgID\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.OrgID))
	}
	{
		const prefix string = ",\"Date\":"
		out.RawString(prefix)
		out.Int64(int64(in.Date))
	}
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix)
		out.Int(int(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v accountStatsRawPoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v accountStatsRawPoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *accountStatsRawPoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *accountStatsRawPoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal4(l, v)
}
func easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(in *jlexer.Lexer, out *accountStatsPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "x":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = int64(in.Int64())
			}
		case "y":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int(in.Int())
			}
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Series = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(out *jwriter.Writer, in accountStatsPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Date))
	}
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix)
		out.Int(int(in.Value))
	}
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix)
		out.Int(int(in.Series))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v accountStatsPoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v accountStatsPoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *accountStatsPoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *accountStatsPoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeGithubComPrivateCaptchaPrivateCaptchaPkgPortal5(l, v)
}
