version: '3'

services:
  server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      PC_PORT: 8080
      PC_POSTGRES: postgres://postgres:postgres@db:5432/privatecaptcha?sslmode=disable
      PC_REDIS: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - postgres_network
      - redis_network

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: privatecaptcha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - redis_network

networks:
  postgres_network:
  redis_network:

volumes:
  postgres_data_volume:
