services:
  server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - pc.env
    environment:
      PC_PORT: 8080
      VERBOSE: 1
    depends_on:
      migration:
        condition: service_completed_successfully
    develop:
      watch:
        - action: rebuild
          path: ../web
        - action: rebuild
          path: ../pkg
        - action: rebuild
          path: ../cmd/server
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pc.env
    networks:
      - postgres_network
      - clickhouse_network
      - server_network

  migration:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command:
      /app/server -mode migrate
    environment:
      PC_POSTGRES: postgres://postgres:postgres@postgres:5432/privatecaptcha?sslmode=disable&search_path=public
      PC_CLICKHOUSE_HOST: clickhouse
      PC_CLICKHOUSE_DB: privatecaptcha
      PC_CLICKHOUSE_USER: default
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ../cmd/server
        - action: rebuild
          path: ../pkg/db
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pc.env
    networks:
      - postgres_network
      - clickhouse_network

  paddlemock:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.paddlemock
    ports:
      - 18080:18080
    env_file:
      - pc.env
    environment:
      SERVER_BASE_URL: http://server:8080/api/
    depends_on:
      server:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: ../cmd/paddlemock
        - action: rebuild
          path: Dockerfile.paddle
    networks:
      - server_network

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: privatecaptcha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -d privatecaptcha
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - postgres_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.8.9-alpine
    environment:
      CLICKHOUSE_DB: privatecaptcha
    ports:
      - '9000:9000' # Native client interface
      - '8123:8123' # HTTP interface
    networks:
      - clickhouse_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8123/?query=SELECT%201 || exit 1
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/myconfig.xml
      - ./clickhouse-users.xml:/etc/clickhouse-server/users.d/myusers.xml
      - clickhouse_data_volume:/var/lib/clickhouse
      # uncomment for debugging
      - ./clickhouse-logs:/var/log/clickhouse-server/
    develop:
      watch:
        - action: sync+restart
          path: clickhouse-config.xml
          target: /etc/clickhouse-server/config.d/myconfig.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  postgres_network:
  clickhouse_network:
  server_network:

volumes:
  postgres_data_volume:
  clickhouse_data_volume:
