services:
  testserver:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.test
    ports:
      - 8080:8080
    environment:
      STAGE: test
      PC_PRIVATE_API_KEY: c669dfd7daa53b63c5565ed29484f1169
      PC_PORT: 8080
      PC_POSTGRES: postgres://postgres:postgres@postgres:5432/privatecaptcha?sslmode=disable
      PC_CLICKHOUSE_HOST: clickhouse
      PC_CLICKHOUSE_DB: privatecaptcha
      PC_CLICKHOUSE_USER: default
      UA_KEY: ea3ad6863f0ba598c01bb561eda18c24fa72b75629baed833fb92a7fde29a5dd3ce1cbd466e5c0a2762034b43127bb11a4dd86f1c8ea3c24ea70da21f5b2201c
      RATE_LIMIT_HEADER: X-REAL-IP
      # VERBOSE: 1
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - test_postgres_network
      - test_clickhouse_network

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: privatecaptcha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -d privatecaptcha
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - test_postgres_network
    volumes:
      - test_postgres_data_volume:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.8.9-alpine
    environment:
      CLICKHOUSE_DB: privatecaptcha
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8123/?query=SELECT%201 || exit 1
      interval: 3s
      timeout: 3s
      retries: 3
    ports:
      - '9000:9000' # Native client interface
      #- '8123:8123' # HTTP interface
    networks:
      - test_clickhouse_network
    volumes:
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/myconfig.xml
      - test_clickhouse_data_volume:/var/lib/clickhouse
      # uncomment for debugging
      # - ./clickhouse-logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  test_postgres_network:
  test_clickhouse_network:

volumes:
  test_postgres_data_volume:
  test_clickhouse_data_volume:
