version: '3'

services:
  server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      PC_PORT: 8080
      PC_POSTGRES: postgres://postgres:postgres@postgres:5432/privatecaptcha?sslmode=disable
        #PC_CLICKHOUSE: clickhouse://pcuser:pcpwd@clickhouse:9000/privatecaptcha?x-multi-statement=true&debug=true
      PC_CLICKHOUSE_HOST: clickhouse
      PC_CLICKHOUSE_DB: privatecaptcha
      PC_CLICKHOUSE_USER: default
      VERBOSE: 1
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - postgres_network
      - clickhouse_network

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: privatecaptcha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -d privatecaptcha
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - postgres_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    environment:
      CLICKHOUSE_DB: privatecaptcha
    ports:
      - '9000:9000' # Native client interface
      - '8123:8123' # HTTP interface
    networks:
      - clickhouse_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/myconfig.xml
      - clickhouse_data_volume:/var/lib/clickhouse
      # uncomment for debugging
      - ./clickhouse-logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  postgres_network:
  clickhouse_network:

volumes:
  postgres_data_volume:
  clickhouse_data_volume:
