{
 "title": "HTTP metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request rate by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[30s])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{code=~\"5..\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service 99 percentile (overall)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90 percentile of each handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[10m])) by (handler, le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}