scrape_configs:
- job_name: privatecaptcha-server
  scrape_interval: 2s
  static_configs:
  - targets:
    - server:9090
- job_name: docker
  static_configs:
    - targets: ["host.docker.internal:9323"]
