name: CI

on:
  push:
    branches:
    - '*'
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - '**/.*.yml'
    - '.vscode/**'
    - '.devcontainer/**'
    tags-ignore:
    - '*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.0

    - uses: actions/checkout@v4

    ###############
    ## Build web ##
    ###############
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install NPM dependencies
      run: npm ci
      working-directory: ./web

    - name: Build web
      run: make build-js

    ##############
    ## Build Go ##
    ##############
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build server
      run: make build-server

    - name: Test
      run: make test
