name: widget
on:
  push:
    branches:
    - '**'
    paths:
    - 'widget/js/**'
    - 'widget/test/**'
    - '.github/workflows/eslint.yml'
    # - 'web/js/**'
    - '!node_modules/**'
    - '!widget/node_modules/**'
    - '!web/node_modules/**'
    tags-ignore:
    - '*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24.x'
          package-manager-cache: false

      - name: Install widget NPM dependencies
        run: npm ci
        working-directory: ./widget

      - name: Run eslint for widget
        run: npm run lint
        working-directory: ./widget

      - name: Run widget tests
        run: npm run test
        working-directory: ./widget
