#!/usr/bin/env bash
set -euo pipefail

env GOFLAGS="-mod=vendor" CGO_ENABLED=0 go test -tags enterprise -short ./...

RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "Push aborted because unit tests failed."
  exit 1
fi

exit 0
